package importcmd

import (
	"context"
	"fmt"
	"io"
	"os"

	"github.com/urfave/cli/v3"

	"github.com/pinkhop/nitpicking/internal/cmdutil"
	"github.com/pinkhop/nitpicking/internal/domain"
	"github.com/pinkhop/nitpicking/internal/iostreams"
	"github.com/pinkhop/nitpicking/internal/ports/driving"
)

// jsonlOutput is the JSON representation of a JSONL import result.
type jsonlOutput struct {
	Action     string           `json:"action"`
	Source     string           `json:"source"`
	Created    int              `json:"created"`
	Skipped    int              `json:"skipped"`
	Failed     int              `json:"failed"`
	SkippedIDs []string         `json:"skipped_ids,omitzero"`
	Errors     []jsonlLineError `json:"errors,omitzero"`
}

// jsonlLineError is a per-line error in the JSON output.
type jsonlLineError struct {
	Line    int    `json:"line"`
	Message string `json:"message"`
}

// JSONLRunInput holds the parameters for the jsonl subcommand's core logic,
// decoupled from CLI flag parsing so it can be tested directly. The command
// reads a JSONL file, validates all lines, then imports them as issues.
type JSONLRunInput struct {
	Service     driving.Service
	Reader      io.Reader
	FilePath    string
	Author      string
	ForceAuthor bool
	JSON        bool
	WriteTo     io.Writer
	ErrWriteTo  io.Writer
	ColorScheme func() *iostreams.ColorScheme
}

// JSONLRun executes the JSONL import pipeline: parse the input, validate all
// lines against the database prefix, then import the validated records as
// issues. Validation errors are reported without creating any issues; import
// errors are reported per-line after partial completion.
func JSONLRun(ctx context.Context, input JSONLRunInput) error {
	lines, err := domain.Parse(input.Reader)
	if err != nil {
		return fmt.Errorf("parsing JSONL: %w", err)
	}

	if len(lines) == 0 {
		if input.JSON {
			return cmdutil.WriteJSON(input.WriteTo, jsonlOutput{
				Action: "import",
				Source: input.FilePath,
			})
		}
		_, _ = fmt.Fprintln(input.WriteTo, "No lines to import.")
		return nil
	}

	// Get database prefix for validation.
	prefix, err := input.Service.GetPrefix(ctx)
	if err != nil {
		return fmt.Errorf("getting database prefix: %w", err)
	}

	// Phase 1: validate.
	validationResult := domain.Validate(lines, prefix)
	if validationResult.HasErrors() {
		return writeValidationErrors(input, validationResult)
	}

	// Phase 2: import.
	importResult, err := input.Service.ImportIssues(ctx, driving.ImportInput{
		Records:       validationResult.Records,
		DefaultAuthor: input.Author,
		ForceAuthor:   input.ForceAuthor,
	})
	if err != nil {
		return fmt.Errorf("importing issues: %w", err)
	}

	return writeImportResult(input, importResult)
}

// writeValidationErrors renders validation errors to the output.
func writeValidationErrors(input JSONLRunInput, result domain.ValidationResult) error {
	if input.JSON {
		errs := make([]jsonlLineError, len(result.Errors))
		for i, e := range result.Errors {
			errs[i] = jsonlLineError{
				Line:    e.Line + 1, // 1-based for user display.
				Message: e.Message,
			}
		}
		return cmdutil.WriteJSON(input.WriteTo, jsonlOutput{
			Action: "validation_failed",
			Source: input.FilePath,
			Failed: len(result.Errors),
			Errors: errs,
		})
	}

	cs := input.ColorScheme()
	_, _ = fmt.Fprintf(input.ErrWriteTo, "%s Validation failed for %s\n\n",
		cs.ErrorIcon(), input.FilePath)

	for _, e := range result.Errors {
		_, _ = fmt.Fprintf(input.ErrWriteTo, "  line %d: %s\n", e.Line+1, e.Message) // #nosec G705 -- e.Message is generated by our own validation, not external input
	}

	return fmt.Errorf("validation failed with %d errors", len(result.Errors))
}

// writeImportResult renders the import outcome to the output.
func writeImportResult(input JSONLRunInput, result driving.ImportOutput) error {
	if input.JSON {
		out := jsonlOutput{
			Action:  "imported",
			Source:  input.FilePath,
			Created: result.Created,
			Skipped: result.Skipped,
			Failed:  result.Failed,
		}
		for _, r := range result.Results {
			if r.Skipped && !r.IssueID.IsZero() {
				// Include the existing issue's ID so callers can trace which
				// issue matched the idempotency label and was deduplicated.
				out.SkippedIDs = append(out.SkippedIDs, r.IssueID.String())
			}
			if r.Err != nil {
				out.Errors = append(out.Errors, jsonlLineError{
					Message: r.Err.Error(),
				})
			}
		}
		return cmdutil.WriteJSON(input.WriteTo, out)
	}

	cs := input.ColorScheme()
	_, _ = fmt.Fprintf(input.WriteTo, "%s Imported %d issues from %s\n",
		cs.SuccessIcon(),
		result.Created,
		input.FilePath)

	if result.Skipped > 0 {
		_, _ = fmt.Fprintf(input.WriteTo, "  Skipped: %d (already imported)\n", result.Skipped)
		for _, r := range result.Results {
			if r.Skipped && !r.IssueID.IsZero() {
				// Report the existing issue's ID so the user can identify
				// which issues were matched by idempotency label.
				_, _ = fmt.Fprintf(input.WriteTo, "    %s (existing)\n", r.IssueID)
			}
		}
	}
	if result.Failed > 0 {
		_, _ = fmt.Fprintf(input.WriteTo, "  Failed: %d\n", result.Failed)
		for _, r := range result.Results {
			if r.Err != nil {
				_, _ = fmt.Fprintf(input.ErrWriteTo, "  %s: %s\n", r.IdempotencyLabel.String(), r.Err)
			}
		}
	}

	return nil
}

// newJSONLCmd constructs the "jsonl" subcommand, which reads a JSONL file and
// creates issues from it. This preserves the behavior of the original "import"
// leaf command under the new "import jsonl" path.
func newJSONLCmd(f *cmdutil.Factory) *cli.Command {
	var (
		jsonOutput  bool
		author      string
		forceAuthor bool
	)

	return &cli.Command{
		Name:      "jsonl",
		Usage:     "Import issues from a JSONL file",
		ArgsUsage: "<file>",
		Description: `Reads a JSONL (newline-delimited JSON) file where each line describes
one issue to create, complete with relationships, labels, comments, and
state transitions. All lines are validated before any issues are created;
if any line fails validation, the entire import is aborted.

Use this for project bootstrapping — seeding an empty database with a
planned backlog — or for restoring a subset of issues from a backup
file. Each line may include an idempotency_label (a key:value string);
lines whose label already exists in the database are silently skipped,
making the import safe to re-run. The --force-author flag overrides
per-line author fields with the --author value, which is useful when
re-importing issues authored by agents that no longer exist.`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:        "author",
				Aliases:     []string{"a"},
				Sources:     cli.EnvVars("NP_AUTHOR"),
				Usage:       "Default author for imported issues (required)",
				Required:    true,
				Category:    cmdutil.FlagCategoryRequired,
				Destination: &author,
			},
			&cli.BoolFlag{
				Name:        "force-author",
				Usage:       "Override per-line authors with --author value",
				Category:    cmdutil.FlagCategorySupplemental,
				Destination: &forceAuthor,
			},
			&cli.BoolFlag{
				Name:        "json",
				Usage:       "Output machine-readable JSON instead of human-readable text",
				Category:    cmdutil.FlagCategorySupplemental,
				Destination: &jsonOutput,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			if cmd.NArg() < 1 {
				return cmdutil.FlagErrorf("JSONL file path is required")
			}
			filePath := cmd.Args().First()

			// Open the JSONL file.
			file, err := os.Open(filePath) // #nosec G304 -- path is provided as a CLI argument
			if err != nil {
				return fmt.Errorf("opening import file: %w", err)
			}
			defer func() {
				_ = file.Close()
			}()

			svc, err := cmdutil.NewTracker(f)
			if err != nil {
				return err
			}

			return JSONLRun(ctx, JSONLRunInput{
				Service:     svc,
				Reader:      file,
				FilePath:    filePath,
				Author:      author,
				ForceAuthor: forceAuthor,
				JSON:        jsonOutput,
				WriteTo:     f.IOStreams.Out,
				ErrWriteTo:  f.IOStreams.ErrOut,
				ColorScheme: f.IOStreams.ColorScheme,
			})
		},
	}
}
